### ISSUE TITLE
Make icons transparent

### ISSUE THREAD

**Issue by aziz** [be5invis/vscode-iconset#12]
Right now, some of icons are using a darkish gray in areas where it should be transparent. It looks ok for now since VS-Code does not allow themeing the sidebar but they're working on the feature and then the icons does not look good on a different color. 
I suggest removing all those background color now to be future proof

**Comment by aziz** [comment]
Any update on this? VS-Code added the theming feature and now with my current theme those darkish gray areas are really annoying.

**Comment by be5invis** [comment]
Fixed in 1.3.0.
