### ISSUE TITLE
Theme not showing after install

### ISSUE THREAD

**Issue by deevincentday** [be5invis/vscode-iconset#20]
In your readme you give an instruction to set File Icon Theme to Nomo Dark.

Where is this?  When I go to the plug in settings I just see disable and uninstall options.  I do not have Icon theme listed in the File menu.  Looked in the view menu and cannot see it there.  I then tried searching help and no luck.

I am not a developer I am a technical author and only need to use VScode to edit markdown documents.  My usual tool is a single source authoring tools such as MadCap Flare or Framemaker.  Both of which you can use out of the box.  However authoring tools do not support markdown due to there being different flavours.

**Comment by deevincentday** [comment]
Ok I have literally gone through the submenu options on the file menu and found it at last.  

Can you change your readme to say:
File > Preferences > File Icon Theme

(screen shot below)

![image](https://user-images.githubusercontent.com/30651204/30535995-1f7a19a2-9c5c-11e7-8e51-4f055b517174.png)

Then select > Noma Dark Icon for Visual Studio Code

(screen shot below)

![image](https://user-images.githubusercontent.com/30651204/30536175-bac5debe-9c5c-11e7-90c8-59e391ec0b08.png)

**Comment by RizwanaSadaf** [comment]
LOL I HAVE THE SAME ISSUE I DON'T EVEN GET IT!
