### ISSUE TITLE
Request: JS icon to .mjs extension

### ISSUE THREAD

**Issue by VitorLuizC** [be5invis/vscode-iconset#21]
Request JS icon to `.mjs` extension.

<img width="204" alt="issue - extensao de icones" src="https://user-images.githubusercontent.com/9027363/31317850-c1a48362-ac1e-11e7-8a5c-ca50640b9da6.png">

MJS extension let us implement node applications using ES2015 module specification. This support was added on v8.5 in this [PR](https://github.com/nodejs/node/pull/14369).

**Comment by be5invis** [comment]
Added in 1.3.3. Closed.
