### ISSUE TITLE
Project has no license

### ISSUE THREAD

**Issue by spoenemann** [be5invis/vscode-iconset#33]
This project doesn't have any license. Please add one, preferably an [open source license](https://opensource.org/licenses) such as MIT.

A license is mandatory for publishing your extension to [Open VSX](https://open-vsx.org/). Its publishing tool [ovsx](https://www.npmjs.com/package/ovsx) offers to automatically add the MIT license when you try to publish without license. See the [Open VSX Wiki](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) for more details.

**Comment by be5invis** [comment]
Fixed. Uses MIT just like Dolch.

**Comment by spoenemann** [comment]
Great! Could you also increase the version number so a new version can be published?

And would you like to start publishing to Open VSX yourself? The publishing guide is here:
https://github.com/eclipse/openvsx/wiki/Publishing-Extensions
