### ISSUE TITLE
Suggestion: generic code file icon

### ISSUE THREAD

**Issue by borgdylan** [be5invis/vscode-iconset#4]
Would it be possible to have a generic code file icon to cover languages that are not supported by default? This icon would be usable by adding manual entries into the config file that use this icon.

**Comment by borgdylan** [comment]
An alternate idea: having an example template in .ai/.svg format that is open-able with a common place vector graphics program such as inkscape that can be used to make custom icons that use letters in the style of the c#/vb icons that are shipped by default.

**Comment by be5invis** [comment]
@borgdylan There is already an .ai in the repo, you can simply open it and edit.
The text is Myraid Bold, resized to 14 pixels high, and aligned to the pixel grid, with slight balancing modifications.

**Comment by borgdylan** [comment]
Thank you!
