### ISSUE TITLE
[question] Transparent SVG?

### ISSUE THREAD

**Issue by Elarcis** [be5invis/vscode-iconset#6]
I noticed that lots of icons actually have a dark filling inside of them (folders, files, etc.).
The filling color not being exactly the same as the treeview background, I find this a bit unnerving.

Is there any reason why it is so? Can I submit a 'transparent' pull request, or would you rather have (and allow) a forked extension?

**Comment by be5invis** [comment]
Semantically, they should be filled because that these icons are not hollow.
But I can darken some of these areas.
If you wan to make a PR, please change the AI file first.

**Comment by be5invis** [comment]
Closed due to inactivity
